site_name: Order Microservice CQRS and Event Sourcing
repo_url: https://github.com/ibm-cloud-architecture/refarch-kc-order-ms
nav:
  - Introduction: index.md
  - From event storming to CQRS microservice:
    - Order subdomain - analysis and design: ddd-applied.md
    - Implementation considerations: implementation-considerations.md
  - Development practices:
    - Build and run locally: build-run.md
    - Deploy to Kubernetes cluster: deployments.md
  - Event sourcing pattern: https://ibm-cloud-architecture.github.io/refarch-eda/design-patterns/event-sourcing
  - CQRS pattern: https://ibm-cloud-architecture.github.io/refarch-eda/design-patterns/cqrs
  - Integration tests: https://ibm-cloud-architecture.github.io/refarch-kc/itg-tests/

theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences
