site_name: Order Microservice CQRS and Event Sourcing
repo_url: https://github.com/ibm-cloud-architecture/refarch-kc-order-ms
nav:
  - From analysis to implementation: ddd-applied.md
  - Implementation considerations: index.md
  - Build and run locally: build-run.md
  - Event sourcing pattern: https://ibm-cloud-architecture.github.io/refarch-eda/evt-microservices/ED-patterns/#event-sourcing
  - CQRS pattern: https://ibm-cloud-architecture.github.io/refarch-eda/evt-microservices/ED-patterns/#command-query-responsibility-segregation-cqrs-pattern.md
  - Kubernetes Deployments: deployments.md

theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences
