# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: us.icr.io/ibmcaseeda/kc-ordercmdms
  tag: latest
  pullPolicy: Always
  pullSecret: browncompute-registry-secret
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
service:
  name: Node
  type: NodePort
  servicePort: 9080
  nodePort: 31200
  servicePortHttps: 9443
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  metrics:
    cpu:
      targetAverageUtilization: 70
    memory:
      targetAverageUtilization: 70
base:
  enabled: false
  replicaCount: 1
  image:
    tag : v0.9.9
  weight: 100
istio:
  enabled: false
  weight: 100
generatedBindings:
  enabled: true
kafka:
  brokersConfigMap: kafka-brokers
eventstreams:
  enabled: true
  apikeyConfigMap: eventstreams-apikey
  truststoreRequired: false
  truststorePath: /config/resources/security/es-ssl
  truststoreFile: es-cert.jks
  truststoreSecret: es-truststore-jks
  truststorePassword: changeit
serviceAccountName: default
