name: Publish order-query Docker
on:
  push:
    paths:
      - 'order-query-ms/**'
  check_run:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ibmcase/kcontainer-order-query-ms
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile.multistage
        workdir: order-query-ms
