name: Build & push docker image
on:
  push:
    branches:
      - master
    paths:
      - 'order-query-ms/**'
env:
  WORKDIR: order-query-ms
  DOCKERFILE: Dockerfile.multistage
  IMAGE_NAME: ibmcase/kcontainer-order-query-ms
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump Versions
      uses: remorses/bump-version@js
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        version_file: ./VERSION
    - name: Build the Docker image
      run: |
        docker login -u ${DOCKER_U} -p ${DOCKER_P}
        TAG_VERSION = $(cat VERSION)
        cd ${WORKDIR}
        docker build . --file ${DOCKERFILE} --tag ${IMAGE_NAME}:${TAG_VERSION}
        docker tag ${IMAGE_NAME}:${TAG_VERSION} ${IMAGE_NAME}:latest
        docker push ${TAG_VERSION}
      env:
        DOCKER_U: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_P: ${{ secrets.DOCKER_PASSWORD }}
